Adding login page
andreyshilov0/front-end-my-favorite-movies pull request #1
Opened 2023-03-11 11:27 UTC by andreyshilov0

2023-03-13 07:31 UTC, Isidora25 requested changes
1. Опять страдает название ветки. Ветка review мне и другим пользователям репозитория не говорит ни о чем. название ветки должно отображать суть изменений
2. Сообщение для коммита уже лучше, но императив - это единственное число повелительное наклонение глагола. Лучше начинать с глагола. Т. О. твое сообщение для коммита должно выглядеть как Add login page

2023-03-13 07:31 UTC, Isidora25 commented on src/custom.d.ts
> +// declare module "*.svg"
Если оно не надо, удаляй из файл кода совсем

2023-03-13 07:31 UTC, Isidora25 commented on src/components/typescript/CheckBoxInput.tsx
> +type Props = FieldRenderProps<boolean, any>;
использовать any - это как говорить тайпскрипту - фу, ты надоел, отстань 
any допускается использовать только тогда, когда у тебя действительно может прийти любой тип и т.д. 
тут как я вижу, оч даже понятно, какой именно тип должен быть `HTMLElement`

2023-03-13 07:31 UTC, Isidora25 commented on src/components/typescript/CheckBoxInput.tsx
> +type Props = FieldRenderProps<boolean, any>;
btw  
в небольших компонентах это незаметно, но по мере разрастания хранить типы в индексе может быть супер неудобно и для типов создают спец файлы в той же директории types.ts

2023-03-13 07:31 UTC, Isidora25 commented on src/components/typescript/TextInput.tsx
> +const TextInput: React.FC<Props> = ({ input, meta, ...rest }: Props) => (
a зачем тебе выносить здесь meta объект, если ты его не используешь? 
тебе он не нужен в inpute?

2023-03-13 07:31 UTC, Isidora25 commented on src/index.tsx
> +}
выноси сразу в другое место, global-styles или что-то подобное

2023-03-13 07:31 UTC, Isidora25 commented on src/index.tsx
> +  <Route path = '/AddFavorite' element={<AddFavorite/>}/>
url для роутов принято писать в kebab-case

2023-03-13 07:31 UTC, Isidora25 commented on src/index.tsx
> +      <RouterProvider router={router} />
Все это логичнее спрятать в App

2023-03-13 07:31 UTC, Isidora25 commented on src/localStorage.ts
> +
пустая строка

2023-03-13 07:31 UTC, Isidora25 commented on src/localStorage.ts
> +export const PASSWORD = localStorage.getItem('password');
Эти переменные не являются константами, так как в ls запросто может не быть объекта  user и password и поэтому они могут принимать null
А какая это константа, если у переменной может быть несколько значений?

2023-03-13 07:31 UTC, Isidora25 commented on src/localStorage.ts
> +        localStorage.setItem('user', 'test')
а вот для ключа 'user' будет классно завести константу USER_KEY или что-то подобное и при получении или установке переменной в хранилище использовать только ее 
удобство в том, что если тебе понадобится поменять ключ этого значения в локал сторадж тебе нужно будет это делать только в одном месте - в определении константы

2023-03-13 07:31 UTC, Isidora25 commented on src/pages/Auth.tsx
> +padding: 5%
все стили лучше хранить в отдельном файле - styles.css

2023-03-13 07:31 UTC, Isidora25 commented on src/pages/Auth.tsx
> +    const password1: string = password as string
1. очень, ОЧЕНЬ плохо использовать в именах переменных цифры 
в чем разница между login и login1? logiin1 не описывает однозначно переменную и ее назначение. имена переменных должны четко и понятно отражать их суть и содержимое
2. для чего тебе переменная login1 если у тебя есть стейт с таким же смыслом и более того ты в эту переменную кладешь тот же самый стейт?

2023-03-13 07:31 UTC, Isidora25 commented on src/pages/Auth.tsx
> +          setDefaultPassword()
Не оч понимаю вот это 
то есть если ты ввел неправильные данные дефолтового пользователя ты все равно его авторизуешь? 
твое приложение должно быть максимально приближено к работе приложения с бэком, потому что тебе потом этот бэк и прикручивать 
не делай лишних движений, которые потом тебе отстрелят обе ноги 
а может и  обе руки

2023-03-13 07:31 UTC, Isidora25 commented on src/pages/Auth.tsx
> +       <div> <img style={{marginLeft: '30%'}} src={logo} alt="logo" /></div>
нам не нужно лого вордпресса в приложении, это был всего лишь пример)) 
можешь заменить его лого, которое больше подходит тематике твоего приложения или удалить совсем

2023-03-13 07:31 UTC, Isidora25 commented on src/pages/Auth.tsx
> +import logo from '../assets/logo-auth.svg'
btw если ты не используешь logo-auth.png - его нужно удалить из проекта

2023-03-13 07:31 UTC, Isidora25 commented on src/pages/Auth.tsx
> +      initialValues={{ stooge: 'larry', employed: false }}
какое отношение к форме логина имеет этот объект начального значения?))) 
правильно, никакого 
удаляй, пожалуйста все то, что не используется и не имеет никакого значения

2023-03-13 07:31 UTC, Isidora25 commented on src/pages/Auth.tsx
> +              </div>
я видела у тебя компонент TextInput, так почему бы его здесь не использовать? 
Прелесть работы с формой в том, что тебе не нужны обработчики на каждое поле (инпут) в ней, ты можешь забирать объект с заполненными данными по событию onSubmit 
тогда ты сможешь избавиться от onChange эвента и явной передачи value вы инпут

2023-03-13 07:31 UTC, Isidora25 commented on src/pages/Auth.tsx
> +          <Field<boolean> name="employed" component="input" type="checkbox" />
как я писала в чате, не нужно реализовывать функционал Запомнить меня и Забыли пароль?

2023-03-13 07:31 UTC, Isidora25 commented on src/pages/Auth.tsx
> +            </button>
для кнопки с типом submit не нужно обработчик onClick 
при нажатии на такую кнопку срабатывает событие submit и соотвтственно срабатывает обраотчик onSubmit

2023-03-13 07:31 UTC, Isidora25 commented on src/pages/Auth.tsx
> +      {isAuth !== true ? <Styles>
эту логику тоже лучше убрать отсюда, так как лучше оставлять компоненту только одну роль/ответственность 
пусть ответственность этого компонента будет - отрисовка страницы Auth, а всем остальным занимается роутер или промежуточный хелпер

2023-03-13 07:31 UTC, Isidora25 commented on src/react-app.env.d.ts
> +/// <reference types="react-scripts" />
почему закомментировано?

2023-03-13 07:31 UTC, Isidora25 commented on src/style/StyleAuth.tsx
> +const btn = (light: string, dark: string) => css`
вопрос, зачем тебе все эти стили если ты установил MUI?

2023-03-13 07:31 UTC, Isidora25 commented on src/style/StyleAuth.tsx
> +`;
Так лучше не делать 
1. Очень сложно читать 
2. Невозможно переиспользовать стили 
3. Очень сложно вносить изменения 

Вместо этого тебе нужно 
1. Использовать готовые стайлед элементы из material UI 
2. Если элементы библиотеки неудовлетворяют твоему мокапу/видению - использовать параметр sx или  функцию styled() для изменения дефолтных стилей

2023-03-13 07:31 UTC, Isidora25 commented on tsconfig.json
> +    "noImplicitAny": false
хитрО, но лучше так не делать в учебном проекте

2023-03-13 07:31 UTC, Isidora25 commented on tsconfig.json
> +    "components/assets/logo-auth.svg"
уверен, что оно тебе надо?

2023-03-13 07:49 UTC, andreyshilov0 commented on src/components/typescript/TextInput.tsx
> +const TextInput: React.FC<Props> = ({ input, meta, ...rest }: Props) => (
Эти компоненты шли вместе с react-final-form я ещё не до конца разобрался с ними, поэтому закинул чтобы просто работало.

2023-03-13 08:12 UTC, andreyshilov0 commented on src/pages/Auth.tsx
> +          setDefaultPassword()
Нет, авторизация не происходит, только закидываются данные дефолтового юзера в localStorage если их там нет

2023-03-13 08:21 UTC, andreyshilov0 commented on src/react-app.env.d.ts
> +/// <reference types="react-scripts" />
Оно в таком состоянии и было при инициализации , не закомментировано

2023-03-13 08:23 UTC, andreyshilov0 commented on src/style/StyleAuth.tsx
> +const btn = (light: string, dark: string) => css`
Делал форму через react-final-form , это прикручено уже туда было, или их лучше совмещать? RFF и MUI?

2023-03-20 09:28 UTC, Isidora25 requested changes

2023-03-20 09:28 UTC, Isidora25 commented on src/components/AuthForm/index.tsx
> +            </Button>
Какая-то беда с форматированием отступов? 
у тебя стоит prettier? 
если нет, настоятельно рекомендую установить

2023-03-20 09:28 UTC, Isidora25 commented on src/components/AuthForm/styles.ts
> +  }
А что это за селектор такой интересный?) 

это работает, потому что для браузера Button = button, но вообще тега Button не существует 
добавь эти стили таким же образов к компоненту Button из MUI как и ко всем остальным

2023-03-20 09:28 UTC, Isidora25 commented on src/components/NavBar/index.tsx
> +      <CustomContainer>
Именование кастом вообще мало о чем говорит, если ее убрать будет то же самое

2023-03-20 09:28 UTC, Isidora25 commented on src/components/NavBar/index.tsx
> +          My Favorite Movies
А почему у тебя на странице логина все по-русски, а тут по-английски? 
следующим ПРом прикрути i18n

2023-03-20 09:28 UTC, Isidora25 commented on src/components/NavBar/styles.ts
> +}));
где-то я уже видела такое
расскажи, пожалуйста, почему ты здесь используешь theme?

2023-03-20 09:28 UTC, Isidora25 commented on src/components/NavBar/styles.ts
> +  margin: "15px 0 15px 0",
это можно короче записать, с помощью сокращенной записи 
`margin: 15px 0;`

2023-03-20 09:28 UTC, Isidora25 commented on src/components/NavBar/styles.ts
> +export const CustomDiv = styled("div")`
для html тегов можно использовать более короткую запись 
styled.div

2023-03-20 09:28 UTC, Isidora25 commented on src/components/NavBar/index.tsx
> +        </CustomDiv>
А что такое CutomDiv? 
Если просто обертка - то Container, Wrapper и т.д.

2023-03-20 09:28 UTC, Isidora25 commented on src/pages/AuthPage/AuthPage.tsx
> +      <img src={logo} alt={'logo'} width={120} height={120} />
в реакте строковые пропсы можно записывать без использовать фигурных скобок

2023-03-20 09:28 UTC, Isidora25 commented on src/pages/AuthPage/styles.ts
> +  margin-top: 10%;
Аккуратнее с такими значениями в процентах, могут выстрелить в ногу во время верстки респонсива
всегда безопаснее использовать фиксированные значение

2023-03-20 09:28 UTC, Isidora25 commented on src/pages/Main.tsx
> +
лишний отступ

2023-03-20 09:28 UTC, Isidora25 commented on src/pages/Main.tsx
> +    <h1 style={{textAlign:"center"}}>Главная страница</h1>
инлайн стили - это опасно, они имеют высокую специфичность и их нельзя переписать без использования слова important

2023-03-20 09:28 UTC, Isidora25 commented on tsconfig.json
> +      "@constants/*": ["constants/*"],
у тебя разве есть папка constants в проете?

2023-03-20 09:28 UTC, Isidora25 commented on src/components/AuthForm/index.tsx
> +import {  CustomTextField,  CustomPaper,} from "./styles";
тут тоже беда с лишними пробелами

2023-03-20 10:49 UTC, Isidora25 requested changes

2023-03-20 10:49 UTC, Isidora25 commented on src/components/AuthForm/styles.ts
> +display:flex;
для стайлед компонентов тоже поставь расширение, тут не хватает пробела 
https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components

2023-03-20 10:49 UTC, Isidora25 commented on src/components/NavBar/index.tsx
> +        Мои избранные фильмы Привет, {localStorage.getItem("user")}!
тут ты зря удалил CustomDiv, надо было просто переименовать

2023-03-20 10:49 UTC, Isidora25 commented on src/components/NavBar/styles.ts
> +export const NavHeader = styled.div`
для хедера можно использовать семантический тег header

2023-03-20 11:44 UTC, Isidora25 requested changes

2023-03-20 11:44 UTC, Isidora25 commented on src/components/NavBar/styles.ts
> +  color: "white";
тут все свойства без кавычек будут работать, а в кавычках нет

2023-03-20 11:50 UTC, Isidora25 approved these changes

2023-03-20 12:23 UTC, reshetov requested changes

2023-03-20 12:23 UTC, reshetov commented on src/components/AuthForm/index.tsx
> +      localStorage.getItem("user") === data.username &&
Лучше это вынести в отдельнюу функцию (что-то вроде isCredentialsValid?) потом проще будет найти по менять на JWT в конце

2023-03-20 12:23 UTC, reshetov commented on src/pages/AuthPage/AuthPage.tsx
> +    localStorage.setItem("user", "test");
Это зачем такое? Лучше оставляй пустыми и в функции проверки пароля проверяй что пароль есть или он правильный

2023-03-20 12:23 UTC, reshetov commented on src/pages/AuthPage/AuthPage.tsx
> +      <img src={logo} alt="logo" width={120} height={120} />
Используй  styled компонент, не нужно inline css

2023-03-20 13:10 UTC, reshetov approved these changes

2023-03-20 13:18 UTC, merged