Task/add main page
andreyshilov0/front-end-my-favorite-movies pull request #2
Opened 2023-03-29 08:04 UTC by andreyshilov0

2023-03-29 09:41 UTC, Isidora25 requested changes

2023-03-29 09:41 UTC, Isidora25 commented on public/locales/en/auth-page.json
> +    "button_login":"Log-in"
нужно использовать единый стиль для именования, тут как и во всем js приложении лучше использовать camelCase

2023-03-29 09:41 UTC, Isidora25 commented on public/locales/en/main-page.json
> +    "NavBar":{
здесь тоже поправь, пожалуйста

2023-03-29 09:41 UTC, Isidora25 commented on public/locales/en/main-page.json
> +
удаляй лишние пробелы

2023-03-29 09:41 UTC, Isidora25 commented on src/api/tmbdAPI.ts
> +  updateSelectedGenres(selectedGenres: number[]) {
отбивай логические куски кода пробелами, так удобнее читать

2023-03-29 09:41 UTC, Isidora25 commented on src/api/tmbdAPI.ts
> +  updateSelectedGenres(selectedGenres: number[]) {
функция называется update**Selected**Genres, а обновляешь ты favoriteGenres
приведи имена к одному смыслу

2023-03-29 09:41 UTC, Isidora25 commented on src/api/tmbdAPI.ts
> +  deleteMovie(movieId: number) {
тут тоже хотелось бы уточнить, какой фильм ты удаляешь

2023-03-29 09:41 UTC, Isidora25 commented on src/components/AuthForm/index.tsx
> +              </LanguageButton>
вынеси это в отдельный компонент, чтобы скрыть в нем всю логику со сменой языка

2023-03-29 09:41 UTC, Isidora25 commented on src/api/tmbdAPI.ts
> +    language: "ru",
а у тебя теперь может быть не только русский язык)

2023-03-29 09:41 UTC, Isidora25 commented on src/components/AuthForm/styles.ts
> +export const ButtonPanel = styled("div")`
styled.div короче

2023-03-29 09:41 UTC, Isidora25 commented on src/components/ButtonAction/index.tsx
> +      </Tooltip>
а что происходит далее с фильмом, который ты отметил как просмотренный? 
почему удаление у тебя совершает какие-то действия, а setIsWatched только локальный стейст обновляет?

2023-03-29 09:41 UTC, Isidora25 commented on src/components/ButtonAction/index.tsx
> +      <Tooltip
Почему ты здесь используешь Tooltip?

2023-03-29 09:41 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +  const [view, setView] = React.useState("list");
импортируй сразу useState

2023-03-29 09:41 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +    event: React.MouseEvent<HTMLElement>,
если параметр event не используется, замени его на _

2023-03-29 09:41 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +  }, []);
пробел

2023-03-29 09:41 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +          >
если объект кликабельный и перенаправляет юзера на другую страницу - это ссылка

2023-03-29 09:41 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +          </ToggleButtonGroup>
задание: перепеши это без ToggleButtonGroup

2023-03-29 09:41 UTC, Isidora25 commented on src/components/FavoriteMovieList/index.tsx
> +    </Paper>
1. Меня не покидает чувство дежавю 
2. В современном css есть возможность верстать таблицеподобные мокапы и без таблиц. Таблицы сложно поддаются резиновой верстке 

Перепеши это без таблиц

2023-03-29 09:41 UTC, Isidora25 commented on src/components/FavoriteMovieListItem/index.tsx
> +          alt="Image"
весь текст лучше держать в локалях

2023-03-29 09:41 UTC, Isidora25 commented on src/components/FavoriteMovieListItem/index.tsx
> +          src={`${getBaseImageUrl(movie?.poster_path)}`}
для чего здесь функция? не вижу, чтобы у тебя были урлы для изображений другого вида

2023-03-29 09:41 UTC, Isidora25 commented on src/components/FavoriteMovieListItem/style.ts
> +export const ImageWrapper = styled("img")`
styled.div

2023-03-29 09:41 UTC, Isidora25 commented on src/components/NavBar/index.tsx
> +          </LanguageButtonNav>
я это уже видела, почему это два раза повторяется? 
если тебе нужен одинаковый функционал в двух местах - это верный признак того, что это нужно выносить в компонент и переиспользовать 
почитай про DRY

2023-03-29 09:41 UTC, Isidora25 commented on src/components/NavBar/styles.ts
> +export const NavHeader = styled("header")`
а для чего ты поменял?

2023-03-29 10:05 UTC, andreyshilov0 commented on src/components/ButtonAction/index.tsx
> +      <Tooltip
Нашел в примере MUI

2023-03-31 15:01 UTC, Isidora25 requested changes

2023-03-31 15:01 UTC, Isidora25 commented on src/api/tmbdAPI.ts
> +  const genres = await instance.get(`genre/movie/list`, {
для асинхронных вызовов внешних апи обязательно нужно добавлять обработчики ошибку 
оберни это в try-catch блок

2023-03-31 15:01 UTC, Isidora25 commented on src/api/tmbdAPI.ts
> +export const getDataMovieById = async (id: number): Promise<Object> => {
конкретизируй тип возврата здесь, пожалуйста

2023-03-31 15:01 UTC, Isidora25 commented on src/components/AuthForm/index.tsx
> +              <LanguageButton />
язык не имеет никакого значения для формы логина, убери его из тега form

2023-03-31 15:01 UTC, Isidora25 commented on src/components/AuthForm/styles.ts
> +  margin: 10px 10px;
`margin: 10px 10px; = margin: 10px;`

2023-03-31 15:01 UTC, Isidora25 commented on src/components/AuthForm/styles.ts
> +
Эти стили используются в компоненте LanguageButton, перенеси их туда. Стили должны лежать там, где они непосредственно  используются

2023-03-31 15:01 UTC, Isidora25 commented on src/components/ButtonAction/index.tsx
> +      <Tooltip
чем он удобен? в сравнении с чем?

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +    <>
здесь не нужен фрагмент, потому что у тебя один корневой тег

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +          </Link>
а зачем тебе кнопка в ссылке? просто добавь ссылке нужные стили, чтобы она выглядела как кнопка

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovie/types.ts
> +export interface IObjectMovieData {}
это нигде не используется, убирай код, которые не нужен

2023-03-31 15:01 UTC, Isidora25 commented on src/components/ButtonAction/index.tsx
> +const ButtonsAction = ({ deleteMovieById, watchedMovie, movie }: any) => {
Никаких any, если тип известны на самом деле

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovieList/index.tsx
> +    JSON.parse(localStorage["backend_data_favorite_movies"])
1. ты вроде как вынес это в обработчик отдельный: getFavoriteMovie
2. избавься от any пожалуйста

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovieList/index.tsx
> +    <>
и тут фргамент не нужен

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovieList/index.tsx
> +            <FavoriteMovieListItem
component FavoriteMovieListItem имеет входящий пропс под именем handleWatchedMovie
здесь ты используешь watchedMovie, магия какая-то)

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovieList/style.ts
> +`;
эта обертка точно нужна?

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovieListItem/index.tsx
> +}: any) => {
any

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovieListItem/index.tsx
> +        watchedMovie={handleWatchedMovie}
проп, который является обработчиком, то есть функцией, должен в своем названии это отображать 
watchedMovie выглядит будто это объект просмотренного фильма
если ты его назовешь handleWatchedMovie будет сильно понятнее

2023-03-31 15:01 UTC, Isidora25 commented on src/components/ButtonAction/index.tsx
> +            setIsWatched(!!watchedMovie(movie.user_watched) ? true : false)
!!watchedMovie(movie.user_watched) уже имеет тип boolean

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovieListItem/types.ts
> +export interface IMovieDataItem {}
тоже не используется

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovieModule/index.tsx
> +      </Table>
Снова таблицы, давай без них

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovieModuleItem/index.tsx
> +}: any) => {
эни

2023-03-31 15:01 UTC, Isidora25 commented on src/components/FavoriteMovieModuleItem/index.tsx
> +        <ButtonsAction />
а почему тут нет никаких пропсов в ButtonsAction?

2023-03-31 15:01 UTC, Isidora25 commented on src/components/LanguageButton/index.tsx
> +const LanguageButton = ({ changeLanguage }: any) => {
any

2023-03-31 15:01 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +  const [genres, setGenres] = useState<any[]>([]);
any

2023-03-31 15:01 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +    localStorage.setItem("backend_data_favorite_genres", JSON.stringify([id]));
это все лучше сразу выносить в отдельные обработчики, потому что когда ты прикрутишь бэк, ты так сделать не сможешь

2023-03-31 15:01 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +    getGenresData("en");
а почему инглиш? тогда у тебя всегда при первом рендеринге инглиш будет, даже когда поменяешь на русский

2023-03-31 15:01 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +      <LanguageButton changeLanguage={changeLanguage} />
а сколько у тебя кнопок смены языка? вообще одна должна быть на приложение

2023-03-31 15:01 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +            }}
onClick={() =>   handleChangeSelected(id)}
```suggestion
            onClick={() => {
              handleChangeSelected(id);
            }}
```

2023-03-31 15:01 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +    <>
фрагмент не нужен

2023-03-31 15:01 UTC, Isidora25 commented on src/components/NavBar/index.tsx
> +  const { t, i18n } = useTranslation("main-page");
i18n не используется в приложении

2023-03-31 15:01 UTC, Isidora25 commented on src/components/NavBar/styles.ts
> +export const NavHeader = styled("header")`
все тот же вопрос)

2023-04-02 11:57 UTC, andreyshilov0 commented on src/components/FavoriteMovieModuleItem/index.tsx
> +        <ButtonsAction />
Я ещё не добрался до форм списков

2023-04-02 12:00 UTC, andreyshilov0 commented on src/components/ListGenre/index.tsx
> +      <LanguageButton changeLanguage={changeLanguage} />
Была ещё  на странице авторизации

2023-04-02 13:16 UTC, andreyshilov0 commented on src/components/ListGenre/index.tsx
> +            }}
Тут, немного не понимаю

2023-04-03 10:04 UTC, Isidora25 requested changes

2023-04-03 10:04 UTC, Isidora25 commented on src/components/FavoriteMovieModuleItem/index.tsx
> +        <ButtonsAction />
в каком смысле?  до каких форм списков?

2023-04-03 10:04 UTC, Isidora25 commented on src/components/FavoriteMovie/style.ts
> +export const ButtonBlock = styled(Button)``;
это больше нигде не используется, удали, плиз

2023-04-03 10:04 UTC, Isidora25 commented on src/components/FavoriteMovieList/types.ts
> +  handleWatchedMovie: Function;
это тоже можно описать более конкретно, чтобы избежать ситуации, когда ты можешь передать функцию с неправильными параметрами

2023-04-03 10:04 UTC, Isidora25 commented on src/components/LanguageButton/types.ts
> +  changeLanguage: Function;
тоже, пожалуйста, уточни

2023-04-03 10:04 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +    isChangeSelectedIdGenres(id);
со слова is обычно именуются переменные-флаги, которые имеют тип boolean 
обработчики обычно именуются со слова handle или другого отражающего смысл глагола 
isChangeGenres - кладет в локал сторадж жанры, так что тут отлично подойдет имя setAllGengresToLocalStorage

2023-04-03 10:04 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +  useEffect(() => {
не очень поняла, зачем тебе вызов двух одинаковых функций тут?

2023-04-03 10:04 UTC, Isidora25 commented on src/api/tmbdAPI.ts
> +  throw new Error("Failed download genres");
тут получается, что ты всегда ошибку выкидываешь, даже когда возвращаешь данные 
тебе не нужно это делать 
в блоке try ты получаешь успешный результат запроса и сразу же возвращаешь его из функции getGenres
в блоке catch ты обрабатываешь ошибку и консолишь ее. Закроем пока глаза на то, что это бессмысленно для юзера и никто не смотрит в консоль. будем считать, что так оно и надо.

2023-04-03 10:04 UTC, Isidora25 commented on src/api/tmbdAPI.ts
> +  throw new Error("Failed download genres");
то же касается и остальных обработчиков

2023-04-03 11:25 UTC, Isidora25 approved these changes

2023-04-03 11:51 UTC, reshetov requested changes

2023-04-03 11:51 UTC, reshetov commented on src/api/tmbdAPI.ts
> +export const getFavoriteMovie = () => {
У тебя этот метод может вернуть больше чем один фильм судя по коду  - лучше его назвать getFavoriteMovies, и тип возвращаемых значений добавь.

2023-04-03 11:51 UTC, reshetov commented on src/components/FavoriteMovieList/index.tsx
> +        {favoriteMovie.map((movie, id) => (
Не путай людей, я вижу favoriteMovie и думаю что там один фильм, а ты его тут итерируешь, иду копать, а там массив

2023-04-03 11:51 UTC, reshetov commented on src/components/LanguageButton/index.tsx
> +      <LanguageButtonStyle onClick={() => changeLanguage("en")}>
Я бы добавил константу я массивом возможных локалей и тут ее смапал, а еще можно о ее заюзать в API модуле, где у тебя языки возврата

2023-04-03 11:51 UTC, reshetov commented on src/components/FavoriteMovieList/index.tsx
> +        {favoriteMovie.map((movie, id) => (
И еще не использую index как key, можешь словить очень веселые бани - https://www.developerway.com/posts/react-key-attribute#part3
Лучше имя или id самого фильма

2023-04-03 11:51 UTC, reshetov commented on src/components/ListGenre/index.tsx
> +      {genres.map((genres, id) => (
См выше про key

2023-04-03 12:17 UTC, reshetov requested changes

2023-04-03 12:17 UTC, reshetov commented on src/api/tmbdAPI.ts
> +const listLanguage = ["ru", "en"];
Еще раз, нужно не переменную, а именно константу добавить чтобы не повторять по всему приложению. А импортировать везде одно и тоже и все.
Сейчас если я тебе скажу "на нужно еще чешский добавить язык" в скольки местах ты будешь исправлять? А я хочу чтобы в одном

2023-04-03 12:17 UTC, reshetov commented on src/api/tmbdAPI.ts
> +const listLanguage = ["ru", "en"];
И переменная у тебя называется "список языкА", а не "список языкОВ"

2023-04-03 12:17 UTC, reshetov commented on src/components/LanguageButton/index.tsx
> +  const listLanguage = ["ru", "en"];
см. комент выше

2023-04-03 12:21 UTC, reshetov requested changes

2023-04-03 12:21 UTC, reshetov commented on src/api/constants.ts
> +export const listLanguages = ["ru", "en"];
А теперь посмотри на две строки выше и скажи что не так с твоей? Не торопись!

2023-04-03 12:32 UTC, reshetov approved these changes

2023-04-03 12:33 UTC, merged