Task/add favorite movies
andreyshilov0/front-end-my-favorite-movies pull request #5
Opened 2023-04-12 10:58 UTC by andreyshilov0

2023-04-12 11:48 UTC, Isidora25 requested changes

2023-04-12 11:48 UTC, Isidora25 commented on public/locales/en/add-favorite.json
> +
пробел лишний

2023-04-12 11:48 UTC, Isidora25 commented on public/locales/ru/add-favorite.json
> +
и тут тоже

2023-04-12 11:48 UTC, Isidora25 commented on public/locales/en/add-favorite.json
> +
и отступ перед "option"

2023-04-12 11:48 UTC, Isidora25 commented on public/locales/en/add-favorite.json
> +        "button-add": "Add to favorite",
соблюдай едиообразие, используй camelCase

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +  const [moviesDate, setMoviesDate] = useState<
moviesData наверное 
date - это дата 
data - это данные

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +  >([]);
если начальное значение пустой массив, то можно обойтись и без undefined и наоборот

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +  const [isSelectButtonMovieId, setIsSelectButtonMovieId] = useState<number[]>(
с префикса is обычно начинаются имена булевых переменных 
и вообще не очень понятно  по названию стейта, за что он отвечает
переименуй плиз

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +  const [moviesId, setMoviesId] = useState<number[]>([]);
moviesId - это один id для многих movies? 
если у тебя здесб массив, который состоит из значений id то понятнее будет movieIds

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +    let newMovieId = [id, ...moviesId];
опять для массива не очень подходящее название переменной

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +    let filterMovies = newMovieId.filter((movie) => movie != null);
вот тут не очень поняла, newMovieId - это массив из id, то есть массив чисел number[]
тогда откуда там объект movie, который может null?
если ты все-таки пробегаешь по всем id и выкидываешь null, то проще не складывать туда null и делать проверку на этапе формирования этого массива

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovie/types.ts
> +  currentDate: number;
переименуй в currentYear

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovie/types.ts
> +  changeGenresId: number[];
changeGenresId - это тоже непонятно что значит 
change - это глагол, с глагола обычно именуют обработчики, а здесь массив 
переименуй плиз

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovieList/index.tsx
> +              />
нужен alt

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovieList/style.ts
> +`;
добавь пробел

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovieList/types.ts
> +  moviesDate: Array<IMovieData> | undefined;
опциональность параметра можно указать с помощью `?`
```suggestion
  moviesDate?: Array<IMovieData>;
```

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovieModule/index.tsx
> +            </AddFavoriteWrapContainer>
на вид все то же самое, что в компоненте выше 
можно обойтись без этого компонента вообще, просто меняя стили для AddFavoriteMovieModule в зависимости от выбранного вида сетки

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovieOption/index.tsx
> +    setDate([...date]);
это можно вынести за пределы компонента, так как на формирование этого массива компонент никак не влияет 
получается, что ты этот массив годов формируешь каждый раз, когда компонент встраивается в приложение 
тебе достаточно сделать это только один раз, когда приложение стартует 
вынеси в хелперы

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovieOption/index.tsx
> +  const [date, setDate] = useState<number[]>([]);
тебе не нужен стейт для этого 
и это снова не date, а years

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovieOption/index.tsx
> +            <option key={index}>{date}</option> // Какой использользовать ключ правильно?
для статических массивов можно и индекс, так как этот массив не будет меняться в время работы приложения 
но вообще можно и key=index+date

2023-04-12 11:48 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +    setMoviesDate([]);
для чего затирать стейт опять?

2023-04-12 11:48 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +    let newMovieId = moviesDate.map((film) => film.id);
ты не меняешь newMovieId, используй const

2023-04-12 11:48 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +    setIsSelectButtonMovieId(JSON.parse(localStorage["movieId"]));
два раза в компоненте повторяется JSON.parse(localStorage["movieId"] - вынеси в хелперы

2023-04-12 11:48 UTC, Isidora25 commented on src/index.tsx
> +// import { CountProvider } from "provider/context";
не используйется ? удаляй

2023-04-12 11:48 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +        setMoviesDate((prev) => prev.concat({ ...res }));
concat - это метод для массивов, а ты туда передаешь объект 

setMoviesDate((prev) => prev.concat(res ? res : []))

2023-04-13 08:39 UTC, Isidora25 requested changes

2023-04-13 08:39 UTC, Isidora25 commented on public/locales/en/add-favorite.json
> +        "altImage" : "Image"
тут тоже отступов многовато
у тебя prettier стоит в vscode?

2023-04-13 08:39 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +    let arrayMovieIds = [id, ...movieIds];
let используется тогда, когда переменную надо мутировать
у тебя переменная далее не меняется никак 
поэтому нужно использовать const 

есть очень простое и полезное правило, как выбрать правильный оператор
создаешь всегда переменную через const 
если далее в коде приходится ее мутировать - меняешь на let

2023-04-13 08:39 UTC, Isidora25 commented on src/components/AddFavoriteMovieItems/style.ts
> +  flex-direction: ${(item) => (item.blockView ? "" : "column")};
flex-direction: "" - не валидное значение, зачем оно? 
пропиши явно row

2023-04-13 08:39 UTC, Isidora25 commented on src/components/AddFavoriteMovieItems/style.ts
> +  flex-wrap: ${(item) => (item.blockView ? "wrap" : "")};
и здесь аналогично, используй значение для  flex-wrap по умолчанию

2023-04-13 08:39 UTC, Isidora25 commented on src/components/AddFavoriteMovieItems/style.ts
> +  display: ${(item) => (item.blockView ? "" : "flex")};
та же история

2023-04-13 08:39 UTC, Isidora25 commented on src/components/AddFavoriteMovieItems/style.ts
> +export const AddMovieButtonList = styled(Button)`
почему List? Кнопка вроде одна

2023-04-13 08:39 UTC, Isidora25 commented on src/components/AddFavoriteMovieItems/style.ts
> +  height: ${(item) => (item.blockView ? "100px" : "")};
не надо так делать, используй всегда конкретный значения или свойства

2023-04-13 08:39 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +import { parseMovieId } from "@components/helpers/isValidAddMoviesId";
два разных импорта из одного файла, объедини

2023-04-13 08:41 UTC, andreyshilov0 commented on public/locales/en/add-favorite.json
> +        "altImage" : "Image"
Он в не активе для JSON файлов был, поправил

2023-04-13 08:50 UTC, andreyshilov0 commented on src/components/AddFavoriteMovieItems/style.ts
> +  flex-direction: ${(item) => (item.blockView ? "" : "column")};
Здесь у меня меняется расположение объектов как раз

2023-04-13 09:00 UTC, Isidora25 approved these changes

2023-04-13 10:20 UTC, reshetov requested changes

2023-04-13 10:20 UTC, reshetov commented on src/api/constants.ts
> +  "https://api.themoviedb.org/3/discover/movie";
DRY (https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself) у тебя уже есть базовый API URL, просто дострой этот до нужного
BASE_API_URL="https://api.themoviedb.org/3/"
DEFAULT_MOVIE_URL = BASE_API_URL + "/movie/"
...
Да и то я не совсем уверен что для каждого URL нужна константа, я бы прямо в классе достраивал на основе BASE_API

2023-04-13 10:20 UTC, reshetov commented on src/components/AddFavoriteMovie/index.tsx
> +        addSelectedMovieById={addSelectedMovieById}
Опять пытаешся под видом ID целый массив пропихнуть - https://engblog.ru/plural-of-nouns
Увижу мать - все ей расскажу

2023-04-13 10:23 UTC, andreyshilov0 commented on src/api/constants.ts
> +  "https://api.themoviedb.org/3/discover/movie";
он у меня и не используется, я просто забыл его удалить видимо

2023-04-13 11:50 UTC, reshetov approved these changes

2023-04-13 11:50 UTC, merged