Task/add apollo client
andreyshilov0/front-end-my-favorite-movies pull request #7
Opened 2023-05-25 14:17 UTC by andreyshilov0

2023-05-26 06:03 UTC, Isidora25 requested changes

2023-05-26 06:03 UTC, Isidora25 commented on src/apollo/client.ts
> +    uri: 'http://localhost:4000/graphql',
перенеси урл в env переменнные

2023-05-26 06:03 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +    id})}
чего-то тут с форматированием беда, поставь расширение в vs code для gql

2023-05-26 06:03 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  const [favoriteMovieAdd, { loading, error }] = useMutation<IFavoriteMovieAction>(FAVORITE_MOVIE_ADD, { refetchQueries: [{ query: FAVORITE_MOVIES }] })
для информации: аполло будет автоматически делать рефетч тех квери, у которых сопадают типы 
допустим, у тебя есть есть запрос списка фильмов, ответ на который описан как IMovie[], если ты мутируешь этот же тип любой мутацией, то запрос IMovie[] обновится атоматически 

я не видела, как описаны твои запросы на бэке, поэтому смотри сам, возможно можно обойтись и без refetchQueries

2023-05-26 06:03 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useTotalPages.ts
> +export const useTotalPages = () => {
а для чего тебе отдельный запрос на общее количество страниц? 
если есть пагинация в запросе, это делается обычно одним запросом

2023-05-26 06:03 UTC, Isidora25 commented on src/components/AddFavoriteMovieOption/hooks/useListMovieByDiscover.ts
> +export const useListMovieByDiscover = () => {
а как параметры  фильтрации попадут в квери? у хука нет никаких параметров входящих

2023-05-26 06:03 UTC, Isidora25 commented on src/components/ButtonAction/types.ts
> +  error: ApolloError
уже видела такое описание типа. Вынеси в какой-то общий тип ICommonApiResponse и расширь его во всех местах, где он нужен 

```
interface ISpecialOne extends  ICommonApiResponse  {
   newProperty: string
}
```

2023-05-26 06:03 UTC, Isidora25 commented on src/components/FavoriteMovie/hooks/useFavoriteMovies.ts
> +export const useFavoriteMovie = () => {
useFavoriteMovieS

2023-05-26 11:20 UTC, Isidora25 requested changes

2023-05-26 11:20 UTC, Isidora25 commented on src/components/ListGenre/types.ts
> +}
это нужно куда-нибудь в глобальные типы, потому что если вдруг ты удалишь ListGenres, то это затронет очень много других компонентов

2023-05-26 11:34 UTC, Isidora25 approved these changes

2023-05-29 09:52 UTC, reshetov requested changes

2023-05-29 09:52 UTC, reshetov commented on src/components/AddFavoriteMovieOption/hooks/useListMovieByDiscover.ts
> +query ListMovieByDiscover($sortBy: string, $page: number, $withGenres: number, $year: number, $voteAverage: number, $popularity: number, $totalPages: number) {
$withGenres в виде number не сроляет, он ждет жанры через запятую (http://joxi.ru/brRQZ4Js7gEdvA.jpg)

2023-05-29 09:52 UTC, reshetov commented on src/components/AddFavoriteMovieOption/types.ts
> +    withGenres: number
см. выше

2023-05-29 14:08 UTC, reshetov approved these changes

2023-05-29 14:08 UTC, merged