Task/rework front work to back rails
andreyshilov0/front-end-my-favorite-movies pull request #8
Opened 2023-06-05 07:46 UTC by andreyshilov0

2023-06-05 08:10 UTC, reshetov requested changes

2023-06-05 08:10 UTC, reshetov commented on src/components/AddFavoriteMovieOption/types.ts
> +
Не оставляй столько пустых строк, там не платят за объем файла)

2023-06-05 08:10 UTC, reshetov commented on src/components/AuthForm/hooks/useUserAuth.ts
> +    if (login === dataUser.login && password === dataUser.password) {
Не не не, фронт вообще не то место куда нужно пароли пересылать и уж тем более хранить их тут и проверять. Логика должна быть вида - ты отправляешь логин/пароль, а в ответ тебе прилетает токен (в дальнейшем) или имя пользователя/логин если ты прошел авторизацию и ничего если не прошел. И вот на этом уже дальше все строится

2023-06-05 08:10 UTC, reshetov commented on src/components/FavoriteMovie/hooks/useFavoriteMovieUpdateWatched.ts
> +        favoriteMovieUpdateWatched(input: {
Оступы не табами а пробелами делай (2 пробела)

2023-06-05 09:05 UTC, Isidora25 requested changes

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +        id: id,
когда имя переменной совпадает с именем поля в объекте, то имя поля можно опустить
```
  variables: {
        id
     }
```

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useListMovieByDiscover.ts
> +      year: year,
когда имя переменной совпадает с именем поля в объекте, то имя поля можно опустить

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useListMovieByDiscover.ts
> +  const listMoviesToDiscover = data && data.listMovieByDiscover;
так будет короче data?.listMovieByDiscover

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +  const [addMovieById, { }] = useFavoriteMovieAdd();
а для чего ты забираещь пустой объект?

2023-06-05 09:05 UTC, Isidora25 commented on src/apollo/client.ts
> +    uri: process.env.REACT_APP_DEFAULT_BACK_END_URL,
добавил новый энв - опиши его в env.example

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
а что за тип такой,  ID?

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +      });
не надо для данных из аполло создавать отдельный стейт, можешь использовать их напрямую в компоненте

и если тебе ничего кроме   id от жанров не нужно ты можешь отдавать только id c бека

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +        setAddSelectedToArrayMovieById(movie.id);
то же самое

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +      });
не очень поняла. А что возвращается в listMoviesToDiscover? 
по названию будто бы список фильмов от внешней апишки? 
Но тогда непонятно, почему каждый фильм содержит в себе информацию про totalPages? это должно быть одно значение же

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +      });
аналогично, стейт не нужен

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AddFavoriteMovieItems/index.tsx
> +  addMovieById,
 так как уровнем выше это нигде не используется, можешь доставать этот коллбэк прямо в этом файле

2023-06-05 09:05 UTC, Isidora25 commented on src/components/AuthForm/hooks/useUserAuth.ts
> +  const { loading, error, data } = useQuery(USER);
здесь аналогично предыдущим хукам нужно передать тип

2023-06-05 09:05 UTC, Isidora25 commented on src/components/NavBar/index.tsx
> +  })
для этого я и просила выносить квери в кастомный хук, чтобы не дублировать код

2023-06-05 09:05 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +            }}
тут для каждого жанра ты создаешь свою анонимную функцию - это не эффективно
вынеси это в хелпер, и передавай параметром  id

2023-06-05 10:36 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
как я понял это graphql тип, потому что если сделать его number он выкидывает ошибку о том что не соответствует типу id , а с этим топом всё работает.

2023-06-05 10:38 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
а на бэке он у тебя как описан?

2023-06-05 11:23 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/index.tsx
> +      });
Там значение меняется каждый раз после запроса так как разное количество фильмов по жанрам, поэтому складывается вместе с массивом фильмов

2023-06-05 11:25 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +      });
покажи, что приходит в listMoviesToDiscover

2023-06-05 12:25 UTC, andreyshilov0 commented on src/components/AuthForm/hooks/useUserAuth.ts
> +    if (login === dataUser.login && password === dataUser.password) {
Тогда можно вариант такой? Этот хук закомментирую пока, а когда до jwt доберусь и пойму как он работает, переделаю так как нужно будет.

2023-06-05 12:50 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/index.tsx
> +      });
![image](https://github.com/andreyshilov0/front-end-my-favorite-movies/assets/95177887/08087205-141d-422d-b5c8-92d5d5de78ef)

 он вот сюда доп параметром докидывал страницы, я сейчас пытаюсь переделать на бэке, потому что он у меня либо страницы либо данные фильмов получает

2023-06-05 12:52 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/index.tsx
> +      });
если отдельным хуком передавать там количество страниц в районе 30 тысяч неизменно без discover запроса

2023-06-05 12:56 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
![image](https://github.com/andreyshilov0/front-end-my-favorite-movies/assets/95177887/f65644ea-98fd-4990-8a6e-2395d41918dd) на бэке как раз ID

2023-06-05 12:58 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
в чем разница между  ID  и String ?

2023-06-05 13:00 UTC, Isidora25 commented on src/components/AddFavoriteMovie/index.tsx
> +      });
это входящие параметры для квери, покажи ответ 
мне непонятно, почему у тебя в каждом объекте фильма хранится значение для ОБЩЕГО числа страниц

2023-06-05 13:00 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
Тобишь можно идентификатор строковым сделать?

2023-06-05 13:05 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
Нет, я же вопрос задала)

2023-06-05 13:08 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/index.tsx
> +      });
![image](https://github.com/andreyshilov0/front-end-my-favorite-movies/assets/95177887/f6b5d5e5-4740-4fb9-8213-af4423470e7a)
вот сюда у меня приходил ответ с количеством страниц, но я сейчас понимаю что это странно как то

2023-06-05 13:09 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
ну ID он число принимает

2023-06-05 13:10 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
тогда почему не Number?

2023-06-05 13:14 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
![image](https://github.com/andreyshilov0/front-end-my-favorite-movies/assets/95177887/6b949d60-027c-424f-b4ad-dcf20bd314a3)
ну изначально при сборке graphql бэк указал ID , а если поставить number то он выдает вот такую ошибку

2023-06-05 13:15 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
Видимо для уникальности он все сущности с ID создает

2023-06-05 13:19 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
что значит при сборке? вот этот код сгенерирован или написан руками? 
![image](https://github.com/andreyshilov0/front-end-my-favorite-movies/assets/14825967/f4a7016a-ebf8-414d-93c7-dcc018c32336)

2023-06-05 13:21 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
Руками, но мне просто Андрей не сказал ничего по поводу типа здесь. Там у каждой созданной сущности свой ID. Ну и в принципе я работаю в данных мутациях только с ID

2023-06-05 13:22 UTC, andreyshilov0 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
а в чем проблема здесь оставить ID? Или это для типизации неправильно? Graphql же вроде как понимает какой тип данных передают

2023-06-06 06:17 UTC, Isidora25 commented on src/components/AddFavoriteMovie/hooks/useFavoriteMovieAdd.ts
> +  mutation FavoriteMovieAdd($id: ID!) {
Это не проблема. Просто ты должен понимать, что ты делаешь, а не бездумно копипастить код из интернета. Когда тебя спрашивают в чем разнца между тем или иным подходом, лучше погуглить ответ на этот вопрос, а не отвечать встречными вопросом.

2023-06-06 12:16 UTC, Isidora25 requested changes

2023-06-06 12:16 UTC, Isidora25 commented on src/components/AuthForm/hooks/useUserAuth.ts
> +  });
почему у тебя возвращается массив юзеров?

2023-06-06 12:16 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +    []
а тут тебе не предлагает линтер зависимости добавить?

2023-06-06 12:21 UTC, andreyshilov0 commented on src/components/ListGenre/index.tsx
> +    []
Нет, я сам пробовал добавлять, у меня наоборот огромное количество запросов полетело

2023-06-06 12:23 UTC, Isidora25 commented on src/components/ListGenre/index.tsx
> +    []
ok

2023-06-06 12:24 UTC, andreyshilov0 commented on src/components/AuthForm/hooks/useUserAuth.ts
> +  });
Graphql возвращает объект с массивом пользователей

2023-06-06 12:27 UTC, andreyshilov0 commented on src/components/AuthForm/hooks/useUserAuth.ts
> +  });
![image](https://github.com/andreyshilov0/front-end-my-favorite-movies/assets/95177887/d6c38d84-7d1f-461e-9ff3-501f9aee2d7e)

2023-06-06 12:42 UTC, Isidora25 approved these changes

2023-06-06 13:22 UTC, reshetov approved these changes

2023-06-06 13:23 UTC, merged