Task/add jwt auth
andreyshilov0/front-end-my-favorite-movies pull request #9
Opened 2023-06-26 14:18 UTC by andreyshilov0

2023-06-27 16:55 UTC, reshetov requested changes

2023-06-27 16:55 UTC, reshetov commented on src/components/AuthForm/types.ts
> +  email: string[];
У тебя может быть несколько почт?

2023-06-27 16:55 UTC, reshetov commented on src/components/AuthForm/hooks/useRenderUserEmail.ts
> +  const email = data?.email;
А есть смысл в safe-operator? Лучше как по мне проверять пусто ли в error и если да - email точно приехал

2023-06-27 16:55 UTC, reshetov commented on src/components/AuthForm/types.ts
> +  password: string;
Зачем в ответе тебе пароль пользователя? Во впервых его в открытом виде нет на беке, а во вторых даже если он там как-то очутится передавать его в открытом виде это поставить крест на безопастности

2023-06-27 16:55 UTC, reshetov commented on src/components/AuthForm/hooks/useSignIn.ts
> +        return { error: t("noValidEmailOrPassword") };
Из за того что у тебя нет единого формата ответа ниже по коду у тебя куда safe-operators. Так плохо. Хорошо - привести все возвраты к единому формату, либо через заполнение переменных по дороге (есть ошибка - кидаем в error, есть данные - кладем в data и потом отдаем все в ответе) либо просто в одном формате отвечай просто оставляй пустым то чего нет

2023-06-27 16:55 UTC, reshetov commented on src/components/AuthForm/index.tsx
> +      if (result?.token && result?.user) {
см. комент выше про формат ответа

2023-06-27 16:55 UTC, reshetov commented on src/components/NavBar/index.tsx
> +  const { email } = useRenderUserEmail();
Каждый раз запрашивать данные так себе идея (у тебя же они приходят в том же логине) ипользуй https://legacy.reactjs.org/docs/context.html и подкидывай их туда

2023-06-28 10:43 UTC, andreyshilov0 commented on src/components/AuthForm/types.ts
> +  password: string;
Это не ответ, я перепишу название, это только для формы логина типизация.

2023-06-29 09:23 UTC, reshetov requested changes

2023-06-29 09:23 UTC, reshetov commented on public/locales/en/main-page.json
> +    "error-email-provider": "useEmail must be inside EmailProvider"
И чем поможет пользователю эта информация?

2023-06-29 09:23 UTC, reshetov commented on public/locales/ru/main-page.json
> +    "error-email-provider": "useEmail должен использоваться внутри EmailProvider"
см. выше

2023-06-29 09:23 UTC, reshetov commented on src/components/AuthForm/index.tsx
> +      const { token, user, error } = await signIn(data.email, data.password);
А смыл создавать тип если ты его все равно передаешь как отдельные параметры? Тогда уж передавай в виде типа одним

2023-06-29 09:23 UTC, reshetov commented on src/components/AuthForm/index.tsx
> +    try {
try тут не особо нужен, если упадет - вывалит в консоль весь трейс, а если упадет у тебя - только ошибку. И так и так - все сломано и нужно чинить, но в первом случае написано будет более детально

2023-06-29 09:23 UTC, reshetov commented on src/components/AuthForm/index.tsx
> +        alert(t("noValidEmailOrPassword"));
1. alert это вообще зашквар в приличном обществе, хочешь что-то показать - пиши в логи, не пугай пользователя.
2. А почему ты думаешь что если токена и пользователя нет то сразу пароль неправильный? А если связь по дороге отвалилась или база не беке чушь какую-то отдала? А у тебя всегда "пароль не тот ввели" :) 
нужно работать в errors - ты же их не просто так заполняешь. Вот и используй тут и чтобы пользователь их видел выкидывай в отдельном поле

2023-06-29 09:23 UTC, reshetov commented on src/components/AuthForm/types.ts
> +  password: string;
А вот и нет, у тебя двумя строками ниже этот же тип используется в ISignInResponseData - а это ответ уже. Вывод - в ответе может быть password (даже то что ты его не пришлешь никогда не дает повод другому программисту не использовать это)
Правильно использовать 2 типа. В одном ты делаешь просто пользователя, а во втором расширяешь первый паролем и юзаешь для формы логина

2023-06-29 09:23 UTC, reshetov commented on src/context/EmailContext.tsx
> +export const useEmail = () => {
Вынеси отдельно в hooks

2023-06-29 09:23 UTC, reshetov commented on src/context/EmailContext.tsx
> +  const context = useContext(EmailContext);
Тут мне не до конца нравиться реализация, ты используешь контекст для email,  но им у тебя обернуто все приложение. Лучше назови это ApplicationContext и относить к нему как к глобальному state приложения, тогда почту|логин можно будет просто в отдельном ключе или объекте хранить и тут доставить

2023-06-29 09:23 UTC, reshetov commented on src/components/AuthForm/hooks/useSignIn.ts
> +      const data = response?.data?.signInUser as ISignInResponseData;
Опять гора safe-operator'ов. И в целом очень мусорный метод. Почисти

2023-06-29 09:23 UTC, reshetov commented on src/pages/NavBarLayout/index.tsx
> +    <EmailProvider>
Для чего эти правки?

2023-07-03 11:33 UTC, reshetov requested changes

2023-07-03 11:33 UTC, reshetov commented on src/components/AuthForm/index.tsx
> +    if (error) {
if (token && user) -> navigate("/main");
else
setErrorAuth(error || t("anErrorOccurred"))

2023-07-03 11:33 UTC, reshetov commented on src/components/AuthForm/hooks/useSignIn.ts
> +
!response.data -> { error: 'Unprocessible entry' }

2023-07-03 11:33 UTC, reshetov commented on src/context/ApplicationContext.tsx
> +    email,
email {
currentEmail
setEmail
}

2023-07-05 09:18 UTC, reshetov requested changes

2023-07-05 09:18 UTC, reshetov commented on src/components/AuthForm/hooks/useSignIn.ts
> +        return { error: "Unprocessable entity", token: "", user: null };
И для чего тебе локали если ты их все равно не используешь?

2023-07-05 09:18 UTC, reshetov commented on src/components/AuthForm/hooks/useSignIn.ts
> +      emailData.setEmail(user.email || null);
А зачем null? Оно и так null будет если данных нет

2023-07-05 09:18 UTC, reshetov commented on src/context/hooks/useEmailContext.tsx
> +    console.error(t("navBar.error-get-email"));
Удали

2023-07-05 09:18 UTC, reshetov commented on src/context/types.ts
> +  currentEmail: string | null;
Тут лучше использовать необязательный параметр
currentEmail?: string
Тогда если данных нет - там просто undefined

2023-07-09 06:08 UTC, merged